# Generated by Django 6.0.4 on 2026-04-15 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_automations', '0005_horillaautomation_schedule_date_field_and_more'),
        ('horilla_mail', '0007_horillamailconfiguration_mailjet_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horillaautomation',
            name='mail_server',
            field=models.ForeignKey(blank=True, help_text='Select the mail server to use for sending emails. If not selected, the primary mail server will be used.', limit_choices_to={'mail_channel': 'outgoing', 'type': 'mailjet'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='horilla_mail.horillamailconfiguration', verbose_name='Outgoing Mail Server'),
        ),
    ]
