# Generated by Django 6.0.4 on 2026-04-16 08:33

import django.db.models.deletion
import horilla_mail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_core', '0012_alter_fieldpermission_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrosoftSSOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_enabled', models.BooleanField(default=False, help_text='Turn on/off Microsoft Single Sign-On', verbose_name='Enable Microsoft SSO')),
                ('client_id', models.CharField(blank=True, help_text='Azure AD Application (Client) ID', max_length=500, null=True, verbose_name='Client ID')),
                ('client_secret', horilla_mail.fields.EncryptedCharField(blank=True, help_text='Azure AD Application Client Secret (will be encrypted)', max_length=1000, null=True, verbose_name='Client Secret')),
                ('tenant_id', models.CharField(blank=True, default='common', help_text="Azure AD Directory (Tenant) ID. Use 'common' for multi-tenant apps.", max_length=500, null=True, verbose_name='Tenant ID')),
                ('auto_provision', models.BooleanField(default=True, help_text='Automatically create user accounts on first Microsoft SSO login', verbose_name='Auto-provision Users')),
                ('allowed_domains', models.TextField(blank=True, help_text='Comma-separated list of allowed email domains. Leave empty to allow all domains. Example: company.com,partner.org', null=True, verbose_name='Allowed Email Domains')),
                ('scopes', models.TextField(blank=True, default='User.Read,email,profile,openid', help_text='Comma-separated list of Microsoft Graph API scopes. Default: User.Read,email,profile,openid', null=True, verbose_name='OAuth Scopes')),
                ('button_text', models.CharField(blank=True, default='Sign in with Microsoft', help_text='Text displayed on the Microsoft SSO button', max_length=100, null=True, verbose_name='Button Text')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horilla_core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Microsoft SSO Settings',
                'verbose_name_plural': 'Microsoft SSO Settings',
            },
        ),
    ]
