# Generated by Django 5.2.3 on 2026-06-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("horilla_core", "0014_add_redirect_protocol_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoDataRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demo_data_records",
                        to="horilla_core.company",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demo Data Record",
                "verbose_name_plural": "Demo Data Records",
                "indexes": [
                    models.Index(
                        fields=["company", "content_type"],
                        name="horilla_core_demo_data_company_content_type_idx",
                    ),
                ],
            },
        ),
    ]
