# Generated by Django 6.0.4 on 2026-05-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("horilla_core", "0014_add_redirect_protocol_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="microsoftssosettings",
            name="scopes",
            field=models.TextField(
                blank=True,
                default="User.Read,email",
                help_text="Comma-separated list of Microsoft Graph API scopes. "
                "Default: User.Read,email (openid and profile are added automatically by MSAL)",
                null=True,
                verbose_name="OAuth Scopes",
            ),
        ),
    ]
