# Generated by Django 6.0.3 on 2026-03-06 18:00

import django.db.models.deletion
import horilla.registry.limiters
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_activity', '0004_alter_activity_status'),
        ('horilla_core', '0011_alter_activetab_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=horilla.registry.limiters.ContentTypeLimiter('activity_related_models'), null=True, on_delete=django.db.models.deletion.CASCADE, to='horilla_core.horillacontenttype', verbose_name='Related Content Type'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Related To'),
        ),
    ]
