# Generated by Django 6.0 on 2026-02-20 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_core', '0010_alter_kanbangroupby_unique_together_and_more'),
        ('opportunities', '0005_delete_bigdealalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultopportunitymember',
            name='team_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_role', to='horilla_core.teamrole', verbose_name='Member Role'),
        ),
        migrations.AlterField(
            model_name='opportunityteammember',
            name='team_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_team_role', to='horilla_core.teamrole', verbose_name='Member Role'),
        ),
    ]
