# Generated by Django 6.0 on 2026-02-20 17:02

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_remove_lead_email_message_id_lead_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadstatus',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Leave blank for default (primary theme colour).', image_field=None, max_length=25, null=True, samples=None, verbose_name='Status Color'),
        ),
    ]
