# Generated by Django 6.0 on 2026-02-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_mail', '0003_horillamailtemplate_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horillamail',
            name='to',
            field=models.TextField(blank=True, help_text='Comma separated recipient email addresses', verbose_name='To'),
        ),
    ]
