# Generated by Django 6.0.4 on 2026-04-15 08:00

import horilla_mail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_mail', '0006_alter_horillamail_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='horillamailconfiguration',
            name='mailjet_api_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mailjet API Key'),
        ),
        migrations.AddField(
            model_name='horillamailconfiguration',
            name='mailjet_secret_key',
            field=horilla_mail.fields.EncryptedCharField(blank=True, max_length=512, null=True, verbose_name='Mailjet Secret Key'),
        ),
        migrations.AlterField(
            model_name='horillamailconfiguration',
            name='type',
            field=models.CharField(choices=[('mail', 'Mail'), ('outlook', 'Outlook'), ('mailjet', 'Mailjet')], max_length=255, verbose_name='Type'),
        ),
    ]
